# Generated by Django 5.0.6 on 2024-08-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_forum_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='community',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='community_forums', to='community.community'),
            preserve_default=False,
        ),
    ]
