# Generated by Django 5.0.6 on 2024-08-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_forum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
