# Generated by Django 5.0.6 on 2024-09-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_message_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
