# Generated by Django 5.0.6 on 2024-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_forum_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
