# Generated by Django 5.0.6 on 2024-08-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklineitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_books', to='reader.userprofile'),
        ),
    ]
