# Generated by Django 5.0.6 on 2024-08-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_booklineitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklineitem',
            name='user_profile',
        ),
    ]
