# Generated by Django 5.0.6 on 2024-08-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_booklineitem_book'),
        ('library', '0006_remove_book_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklineitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookdetails', to='library.book'),
        ),
    ]
